# Exemple pour un module
# demoModule:
# 	name_url: demo
#	resource: ""  //adresse du fichier de routing du module


configModule:
	name_url: configuration_webPlane1.0
	resource: "noyau/configModule"

defaultModule: 
	name_url: /
	resource: "module/defaultModule"

userModule:
	name_url: user
	resource: "module/userModule"