# Exemple pour un module
# name_route:
#   name_url: demo
#   resource: ""  //adresse du fichier à charger OU
#   controller: nom_controller:nom_fonction  //Fonction à charger dans le controller

config_index:
    name_url: home
    controller: ConfigController:indexConfig
    
config_urlBase:
    name_url: url
    controller: ConfigController:urlBaseConfig
    
config_bd:
    name_url: bd
    controller: ConfigController:bdConfig