# Exemple pour un module
# name_route:
#   name_url: demo
#   resource: ""  //adresse du fichier à charger OU
#   controller: nom_controller:nom_fonction  //Fonction à charger dans le controller

config_index:
    name_url: home
    controller: ConfigController:indexConfig
    
config_bd:
    name_url: bd
    controller: ConfigController:bdConfig

config_site:
	name_url: site
	controller: ConfigController:siteConfig

config_fin:
	name_url: succes
	controller: ConfigController:finConfig